previewsEnabled: true
databases:
  - name: rails-canary
    databaseName: rails-canary
    user: rails-canary

services:
  - type: web
    name: rails-canary
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: RAILS_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: rails-canary
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: redis
          type: pserv
          property: connectionString
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: PERMITTED_USERS
        value: someone@email.com
      - key: PERMITTED_SENDERS
        value: someone@email.com
  - type: pserv
    name: redis
    env: docker
    repo: https://github.com/render-examples/redis.git 
    disk:
        name: redis-data
        mountPath: /var/lib/redis
        sizeGB: 10